/**
 * Generated by Scrooge
 *   version: 4.7.0-SNAPSHOT
 *   rev: 5979724d4ac92f6b895847e0ebc7a5a67475fa85
 *   built at: 20160604-114938
 */
package de.envisia.sapi.notifications

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object Notification extends ThriftStructCodec3[Notification] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("Notification")
  val IdField = new TField("id", TType.I32, 1)
  val IdFieldManifest = implicitly[Manifest[Int]]
  val MailTypField = new TField("mail_typ", TType.ENUM, 2)
  val MailTypFieldI32 = new TField("mail_typ", TType.I32, 2)
  val MailTypFieldManifest = implicitly[Manifest[de.envisia.sapi.notifications.models.MailType]]
  val ClientIdField = new TField("client_id", TType.I32, 3)
  val ClientIdFieldManifest = implicitly[Manifest[Int]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      IdField,
      false,
      true,
      IdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      MailTypField,
      false,
      true,
      MailTypFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      ClientIdField,
      true,
      false,
      ClientIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: Notification): Unit = {
    if (_item.mailTyp == null) throw new TProtocolException("Required field mailTyp cannot be null")
  }

  def withoutPassthroughFields(original: Notification): Notification =
    new Immutable(
      id =
        {
          val field = original.id
          field
        },
      mailTyp =
        {
          val field = original.mailTyp
          field
        },
      clientId =
        {
          val field = original.clientId
          field.map { field =>
            field
          }
        }
    )

  override def encode(_item: Notification, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): Notification = {

    var id: Int = 0
    var _got_id = false
    var mailTyp: de.envisia.sapi.notifications.models.MailType = null
    var _got_mailTyp = false
    var client_idOffset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
    
                id = readIdValue(_iprot)
                _got_id = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'id' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                mailTyp = readMailTypValue(_iprot)
                _got_mailTyp = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'mailTyp' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 =>
                client_idOffset = _iprot.offsetSkipI32
    
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'clientId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_id) throw new TProtocolException("Required field 'id' was not found in serialized data for struct Notification")
    if (!_got_mailTyp) throw new TProtocolException("Required field 'mailTyp' was not found in serialized data for struct Notification")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      id,
      mailTyp,
      client_idOffset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): Notification =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): Notification = {
    var id: Int = 0
    var _got_id = false
    var mailTyp: de.envisia.sapi.notifications.models.MailType = null
    var _got_mailTyp = false
    var clientId: _root_.scala.Option[Int] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
                id = readIdValue(_iprot)
                _got_id = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'id' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                mailTyp = readMailTypValue(_iprot)
                _got_mailTyp = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'mailTyp' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 =>
                clientId = _root_.scala.Some(readClientIdValue(_iprot))
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'clientId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_id) throw new TProtocolException("Required field 'id' was not found in serialized data for struct Notification")
    if (!_got_mailTyp) throw new TProtocolException("Required field 'mailTyp' was not found in serialized data for struct Notification")
    new Immutable(
      id,
      mailTyp,
      clientId,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    id: Int,
    mailTyp: de.envisia.sapi.notifications.models.MailType,
    clientId: _root_.scala.Option[Int] = _root_.scala.None
  ): Notification =
    new Immutable(
      id,
      mailTyp,
      clientId
    )

  def unapply(_item: Notification): _root_.scala.Option[scala.Product3[Int, de.envisia.sapi.notifications.models.MailType, Option[Int]]] = _root_.scala.Some(_item)


  @inline private def readIdValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeIdField(id_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(IdField)
    writeIdValue(id_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeIdValue(id_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(id_item)
  }

  @inline private def readMailTypValue(_iprot: TProtocol): de.envisia.sapi.notifications.models.MailType = {
    de.envisia.sapi.notifications.models.MailType.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeMailTypField(mailTyp_item: de.envisia.sapi.notifications.models.MailType, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(MailTypFieldI32)
    writeMailTypValue(mailTyp_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeMailTypValue(mailTyp_item: de.envisia.sapi.notifications.models.MailType, _oprot: TProtocol): Unit = {
    _oprot.writeI32(mailTyp_item.value)
  }

  @inline private def readClientIdValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeClientIdField(clientId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ClientIdField)
    writeClientIdValue(clientId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeClientIdValue(clientId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(clientId_item)
  }


  object Immutable extends ThriftStructCodec3[Notification] {
    override def encode(_item: Notification, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): Notification = Notification.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[Notification] = Notification.metaData
  }

  /**
   * The default read-only implementation of Notification.  You typically should not need to
   * directly reference this class; instead, use the Notification.apply method to construct
   * new instances.
   */
  class Immutable(
      val id: Int,
      val mailTyp: de.envisia.sapi.notifications.models.MailType,
      val clientId: _root_.scala.Option[Int],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends Notification {
    def this(
      id: Int,
      mailTyp: de.envisia.sapi.notifications.models.MailType,
      clientId: _root_.scala.Option[Int] = _root_.scala.None
    ) = this(
      id,
      mailTyp,
      clientId,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val id: Int,
      val mailTyp: de.envisia.sapi.notifications.models.MailType,
      client_idOffset: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends Notification {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val clientId: _root_.scala.Option[Int] =
      if (client_idOffset == -1)
        None
      else {
        Some(_proto.decodeI32(_buf, client_idOffset))
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the Notification trait with additional state or
   * behavior and implement the read-only methods from Notification using an underlying
   * instance.
   */
  trait Proxy extends Notification {
    protected def _underlying_Notification: Notification
    override def id: Int = _underlying_Notification.id
    override def mailTyp: de.envisia.sapi.notifications.models.MailType = _underlying_Notification.mailTyp
    override def clientId: _root_.scala.Option[Int] = _underlying_Notification.clientId
    override def _passthroughFields = _underlying_Notification._passthroughFields
  }
}

trait Notification
  extends ThriftStruct
  with scala.Product3[Int, de.envisia.sapi.notifications.models.MailType, Option[Int]]
  with java.io.Serializable
{
  import Notification._

  def id: Int
  def mailTyp: de.envisia.sapi.notifications.models.MailType
  def clientId: _root_.scala.Option[Int]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = id
  def _2 = mailTyp
  def _3 = clientId


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeIdValue(id, _oprot)
                _root_.scala.Some(Notification.IdField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (mailTyp ne null) {
                writeMailTypValue(mailTyp, _oprot)
                _root_.scala.Some(Notification.MailTypField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (clientId.isDefined) {
                writeClientIdValue(clientId.get, _oprot)
                _root_.scala.Some(Notification.ClientIdField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): Notification = {
    var id: Int = this.id
    var mailTyp: de.envisia.sapi.notifications.models.MailType = this.mailTyp
    var clientId: _root_.scala.Option[Int] = this.clientId
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        id = readIdValue(_blob.read)
      case 2 =>
        mailTyp = readMailTypValue(_blob.read)
      case 3 =>
        clientId = _root_.scala.Some(readClientIdValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      id,
      mailTyp,
      clientId,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): Notification = {
    var id: Int = this.id
    var mailTyp: de.envisia.sapi.notifications.models.MailType = this.mailTyp
    var clientId: _root_.scala.Option[Int] = this.clientId

    _fieldId match {
      case 1 =>
        id = 0
      case 2 =>
        mailTyp = null
      case 3 =>
        clientId = _root_.scala.None
      case _ =>
    }
    new Immutable(
      id,
      mailTyp,
      clientId,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetId: Notification = unsetField(1)

  def unsetMailTyp: Notification = unsetField(2)

  def unsetClientId: Notification = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    Notification.validate(this)
    _oprot.writeStructBegin(Struct)
    writeIdField(id, _oprot)
    if (mailTyp ne null) writeMailTypField(mailTyp, _oprot)
    if (clientId.isDefined) writeClientIdField(clientId.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    id: Int = this.id,
    mailTyp: de.envisia.sapi.notifications.models.MailType = this.mailTyp,
    clientId: _root_.scala.Option[Int] = this.clientId,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): Notification =
    new Immutable(
      id,
      mailTyp,
      clientId,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[Notification]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[Notification]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.id
    case 1 => this.mailTyp
    case 2 => this.clientId
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "Notification"
}