/**
 * Generated by Scrooge
 *   version: 4.7.0-SNAPSHOT
 *   rev: 5979724d4ac92f6b895847e0ebc7a5a67475fa85
 *   built at: 20160604-114938
 */
package de.envisia.sapi.notifications

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftService, ThriftStruct,
  ThriftStructCodec, ThriftStructCodec3,
  ThriftStructFieldInfo, ThriftResponse, ThriftUtil, ToThriftService}
import com.twitter.finagle.{service => ctfs}
import com.twitter.finagle.thrift.{Protocols, ThriftClientRequest, ThriftServiceIface}
import com.twitter.util.Future
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.transport.TTransport
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.TMemoryBuffer
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.{
  Builder,
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}
import scala.language.higherKinds


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
trait NotificationService[+MM[_]] extends ThriftService {
  
  def sendNotification(notification: de.envisia.sapi.notifications.models.Notification): MM[Unit]
}



object NotificationService { self =>

  case class ServiceIface(
      sendNotification : com.twitter.finagle.Service[self.SendNotification.Args, self.SendNotification.Result]
  ) extends BaseServiceIface

  // This is needed to support service inheritance.
  trait BaseServiceIface extends ToThriftService {
    def sendNotification : com.twitter.finagle.Service[self.SendNotification.Args, self.SendNotification.Result]

    override def toThriftService: ThriftService = new MethodIface(this)
  }

  implicit object ServiceIfaceBuilder
    extends com.twitter.finagle.thrift.ServiceIfaceBuilder[ServiceIface] {
      def newServiceIface(
        binaryService: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
        pf: TProtocolFactory = Protocols.binaryFactory(),
        stats: com.twitter.finagle.stats.StatsReceiver
      ): ServiceIface =
        new ServiceIface(
          sendNotification = ThriftServiceIface(self.SendNotification, binaryService, pf, stats)
      )
  }

  class MethodIface(serviceIface: BaseServiceIface)
    extends NotificationService[Future] {
    private[this] val __sendNotification_service =
      ThriftServiceIface.resultFilter(self.SendNotification) andThen serviceIface.sendNotification
    def sendNotification(notification: de.envisia.sapi.notifications.models.Notification): Future[Unit] =
      __sendNotification_service(self.SendNotification.Args(notification)).unit
  }

  implicit object MethodIfaceBuilder
    extends com.twitter.finagle.thrift.MethodIfaceBuilder[ServiceIface, NotificationService[Future]] {
    def newMethodIface(serviceIface: ServiceIface): NotificationService[Future] =
      new MethodIface(serviceIface)
  }

  object SendNotification extends com.twitter.scrooge.ThriftMethod {
    
    object Args extends ThriftStructCodec3[Args] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("sendNotification_args")
      val NotificationField = new TField("notification", TType.STRUCT, 1)
      val NotificationFieldManifest = implicitly[Manifest[de.envisia.sapi.notifications.models.Notification]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          NotificationField,
          false,
          false,
          NotificationFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Args): Unit = {
      }
    
      def withoutPassthroughFields(original: Args): Args =
        new Args(
          notification =
            {
              val field = original.notification
              de.envisia.sapi.notifications.models.Notification.withoutPassthroughFields(field)
            }
        )
    
      override def encode(_item: Args, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Args = {
        var notification: de.envisia.sapi.notifications.models.Notification = null
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 1 =>
                _field.`type` match {
                  case TType.STRUCT =>
                    notification = readNotificationValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.STRUCT
                    throw new TProtocolException(
                      "Received wrong type for field 'notification' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Args(
          notification,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        notification: de.envisia.sapi.notifications.models.Notification
      ): Args =
        new Args(
          notification
        )
    
      def unapply(_item: Args): _root_.scala.Option[de.envisia.sapi.notifications.models.Notification] = _root_.scala.Some(_item.notification)
    
    
      @inline private def readNotificationValue(_iprot: TProtocol): de.envisia.sapi.notifications.models.Notification = {
        de.envisia.sapi.notifications.models.Notification.decode(_iprot)
      }
    
      @inline private def writeNotificationField(notification_item: de.envisia.sapi.notifications.models.Notification, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(NotificationField)
        writeNotificationValue(notification_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeNotificationValue(notification_item: de.envisia.sapi.notifications.models.Notification, _oprot: TProtocol): Unit = {
        notification_item.write(_oprot)
      }
    
    
    }
    
    class Args(
        val notification: de.envisia.sapi.notifications.models.Notification,
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftStruct
      with scala.Product1[de.envisia.sapi.notifications.models.Notification]
      with java.io.Serializable
    {
      import Args._
      def this(
        notification: de.envisia.sapi.notifications.models.Notification
      ) = this(
        notification,
        Map.empty
      )
    
      def _1 = notification
    
    
    
      override def write(_oprot: TProtocol): Unit = {
        Args.validate(this)
        _oprot.writeStructBegin(Struct)
        if (notification ne null) writeNotificationField(notification, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        notification: de.envisia.sapi.notifications.models.Notification = this.notification,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Args =
        new Args(
          notification,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Args]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Args]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 1
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.notification
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Args"
    }

    type SuccessType = Unit
    
    object Result extends ThriftStructCodec3[Result] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("sendNotification_result")
      val ErrorField = new TField("error", TType.STRUCT, 1)
      val ErrorFieldManifest = implicitly[Manifest[de.envisia.sapi.notifications.models.NotificationError]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          ErrorField,
          true,
          false,
          ErrorFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Result): Unit = {
      }
    
      def withoutPassthroughFields(original: Result): Result =
        new Result(
          error =
            {
              val field = original.error
              field.map { field =>
                de.envisia.sapi.notifications.models.NotificationError.withoutPassthroughFields(field)
              }
            }
        )
    
      override def encode(_item: Result, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Result = {
        var error: _root_.scala.Option[de.envisia.sapi.notifications.models.NotificationError] = _root_.scala.None
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 1 =>
                _field.`type` match {
                  case TType.STRUCT =>
                    error = _root_.scala.Some(readErrorValue(_iprot))
                  case _actualType =>
                    val _expectedType = TType.STRUCT
                    throw new TProtocolException(
                      "Received wrong type for field 'error' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Result(
          error,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        error: _root_.scala.Option[de.envisia.sapi.notifications.models.NotificationError] = _root_.scala.None
      ): Result =
        new Result(
          error
        )
    
      def unapply(_item: Result): _root_.scala.Option[_root_.scala.Option[de.envisia.sapi.notifications.models.NotificationError]] = _root_.scala.Some(_item.error)
    
    
      @inline private def readErrorValue(_iprot: TProtocol): de.envisia.sapi.notifications.models.NotificationError = {
        de.envisia.sapi.notifications.models.NotificationError.decode(_iprot)
      }
    
      @inline private def writeErrorField(error_item: de.envisia.sapi.notifications.models.NotificationError, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(ErrorField)
        writeErrorValue(error_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeErrorValue(error_item: de.envisia.sapi.notifications.models.NotificationError, _oprot: TProtocol): Unit = {
        error_item.write(_oprot)
      }
    
    
    }
    
    class Result(
        val error: _root_.scala.Option[de.envisia.sapi.notifications.models.NotificationError],
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftResponse[Unit] with ThriftStruct
      with scala.Product1[Option[de.envisia.sapi.notifications.models.NotificationError]]
      with java.io.Serializable
    {
      import Result._
      def this(
        error: _root_.scala.Option[de.envisia.sapi.notifications.models.NotificationError] = _root_.scala.None
      ) = this(
        error,
        Map.empty
      )
    
      def _1 = error
    
      def successField: Option[Unit] = Some(Unit)
      def exceptionFields: Iterable[Option[com.twitter.scrooge.ThriftException]] = Seq(error)
    
    
      override def write(_oprot: TProtocol): Unit = {
        Result.validate(this)
        _oprot.writeStructBegin(Struct)
        if (error.isDefined) writeErrorField(error.get, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        error: _root_.scala.Option[de.envisia.sapi.notifications.models.NotificationError] = this.error,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Result =
        new Result(
          error,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Result]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Result]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 1
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.error
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Result"
    }

    type FunctionType = Function1[Args,Future[Unit]]
    type ServiceType = com.twitter.finagle.Service[Args, Result]

    private[this] val toResult = (res: SuccessType) => Result()

    def functionToService(f: FunctionType): ServiceType = {
      com.twitter.finagle.Service.mk { args: Args =>
        f(args).map(toResult)
      }
    }

    def serviceToFunction(svc: ServiceType): FunctionType = { args: Args =>
      ThriftServiceIface.resultFilter(this).andThen(svc).apply(args)
    }

    val name = "sendNotification"
    val serviceName = "NotificationService"
    val argsCodec = Args
    val responseCodec = Result
    val oneway = false
  }

  // Compatibility aliases.
  val sendNotification$args = SendNotification.Args
  type sendNotification$args = SendNotification.Args

  val sendNotification$result = SendNotification.Result
  type sendNotification$result = SendNotification.Result


  trait FutureIface extends NotificationService[Future] {
    
    def sendNotification(notification: de.envisia.sapi.notifications.models.Notification): Future[Unit]
  }

  class FinagledClient(
      service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
      protocolFactory: TProtocolFactory = Protocols.binaryFactory(),
      serviceName: String = "NotificationService",
      stats: com.twitter.finagle.stats.StatsReceiver = com.twitter.finagle.stats.NullStatsReceiver,
      responseClassifier: ctfs.ResponseClassifier = ctfs.ResponseClassifier.Default)
    extends NotificationService$FinagleClient(
      service,
      protocolFactory,
      serviceName,
      stats,
      responseClassifier)
    with FutureIface {

    def this(
      service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
      protocolFactory: TProtocolFactory,
      serviceName: String,
      stats: com.twitter.finagle.stats.StatsReceiver
    ) = this(service, protocolFactory, serviceName, stats, ctfs.ResponseClassifier.Default)
  }

  class FinagledService(
      iface: FutureIface,
      protocolFactory: TProtocolFactory)
    extends NotificationService$FinagleService(
      iface,
      protocolFactory)
}